"""Add priority column to Task

Revision ID: cec445bd269a
Revises: 5615ccc87008
Create Date: 2025-11-04 16:56:44.109869

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cec445bd269a"
down_revision: str | Sequence[str] | None = "5615ccc87008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("priority", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "priority")
    # ### end Alembic commands ###
